config/routes.rb
Rails.application.routes.draw do
  resources :cards
  get 'people/find'
  post 'people/find'
  resources :people
  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'
  get 'msgboard/index'
  post 'msgboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello', to: 'hello#index'
  get 'hello/index'
  post 'hello', to: 'hello#index'
  post 'hello/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  layout 'cards'
  
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    if request.post? then
      Card.create(card_params)
      goback
    else
      @card = Card.new
    end
  end

  def edit
    @card = Card.find(params[:id])
    if request.patch? then
      @card.update(card_params)
      goback
    end
  end

  def delete
    Card.find(parama[:id]).destroy
    goback
  end

  private
  def card_params
    params.require(:card).permit(:title, :author, :price, :publisher, :memo)
  end

  def goback
    redirect_to '/cards'
  end
  
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'hello'

  def index
    @header = 'layout sample'
    @footer = 'copyright SYODA-TUYAO 2020.'
    @title = 'New Layout'
    @msg = 'this is sample page!'
  end

end

app/controllers/msgboard_controller.rb
class MsgboardController < ApplicationController
  layout 'msgboard'

  def initialize
    super
    begin
      @msg_data = JSON.parse(File.read("data.txt"))
    rescue
      @msg_data = Hash.new
    end
    @msg_data.each do |key,obj|
      if Time.now.to_i - key.to_i > 24*60*60 then
        @msg_data.delete(key)
      end
    end
    File.write("data.txt", @msg_data.to_json)
  end

  def index
    if request.post? then
      obj = MyData.new(msg:params['msg'], name:params['name'], mail:params['mail'])
      @msg_data[Time.now.to_i] = obj
      data = @msg_data.to_json
      File.write("data.txt", data)
      @msg_data = JSON.parse(data)
    end
  end
end

class MyData
  attr_accessor :name
  attr_accessor :mail
  attr_accessor :msg
 
  def initialize msg:msg, name:name, mail:mail
    self.name = name
    self.mail = mail
    self.msg = msg
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  layout 'people'

  def index
    @msg = 'Person data.'
    @data = Person.all
  end

  def show
    @msg = "Indexed data."
    @data = Person.find(params[:id])
  end

  def new
    @msg = "add new data."
    @person = Person.new
  end

  def create
    if request.post? then
     Person.create(person_params)
    end
    redirect_to '/people'
  end

  def edit
    @msg = " edit data.[id = " + params[:id] + "] "
    @person = Person.find(params[:id])
  end

  def update
    obj = Person.find(params[:id])
    obj.update(person_params)
    redirect_to '/people'
  end

  def delete
    obj = Person.find(params[:id])
    obj.destroy
    if obj.save
      redirect_to '/people'
    end
  end

  def find
    @msg = 'please type search word...'
    @people = Array.new
    if request.post? then
      obj = Person.find params['find']
      @people.push obj
    end
  end

  private
  def person_params
    params.require(:person).permit(:name, :age, :mail)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/msgboard_helper.rb
module MsgboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cards/edit.html.erb
<h1 class="display-4 text-primary">Cards#Edition</h1>
<p>※「<% @catd.title %>」の内容を編集します。</p>
<%= form_with model: @cards, local :true do |f| %>
  <div class="form-group">
    <%= f.label :タイトル%>
    <%= f.text_field :title, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :著者%>
    <%= f.text_field :author, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :価格%>
    <%= f.text_field :price, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :出版社%>
    <%= f.text_field :publisher, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :コメント%>
    <%= f.text_area :memo, class:"form_control" %>
  </div>
  <%= f.submit "保存" %>
<% end %>
<p class="link"><a href="cards">
  &lt;&lt; ※トップページに戻る
</a></p>

app/views/cards/index.html.erb
<h1 class="display-4 text-primary">Cards#index</h1>
<p> ※現在、登録されているデータの一覧です。</p>
<table class="table">
  <tr>
    <th>ID</th><th>題名</th><th>著者</th><th colspan="2"></th>
  </tr>
  <% @cards.each do |obj| %>
    <tr>
    <td width="35px"><%= obj.id %></td>
    <td width="50%"><a href="/cards/<%= obj.id %>"><%= obj.title %></a></td>
    <td><%= obj.author %></td>
    <td width="80px"><%= <%= link_to cards_edit_path(obj.id) %>%>編集</a></td>
    <td width="80px">
      <a href="javascript:delData(
        <%= (obj.id.to_s + ",'".to_s + obj.title.to_s).html_safe %>');">削除
      </a>
    </td>
    </tr>
  <% end %>
</table>
<p><a href="/cards/new">※新しいデータを入力&gt;&gt;</a></p>
<script>
function delData(id, title) {
  if (confirm('「' + title + '」のデータ削除しますか？')) {
    document.location = "/cards/delete/" + id;
  }
}
</script>

app/views/cards/new.html.erb
<h1 class="display-4 text-primary">Cards#new</h1>
<p>※登録する読書データを入力してください。</p>
<%= form_with model: @cards, local :true do |f| %>
  <div class="form-group">
    <%= f.label :タイトル%>
    <%= f.text_field :title, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :著者%>
    <%= f.text_field :author, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :価格%>
    <%= f.text_field :price, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :出版社%>
    <%= f.text_field :publisher, class:"form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :コメント%>
    <%= f.text_area :memo, class:"form_control" %>
  </div>
  <%= f.submit "保存" %>
<% end %>
<p class="link"><a href="cards">
  &lt;&lt; ※トップページに戻る
</a></p>

app/views/cards/show.html.erb
<h1 class="display-4 text-primary">Cards#show</h1>>
<p>※「<%= @card.title %>」の読書データ</p>
<table class="table">
  <tr>
    <th width="200">ID</th><td><%= @card.id %></td>
  </tr>
  <tr>
    <th>タイトル</th><td><%= @card.title %></td>
  </tr>
  <tr>
    <th>著者</th><td><%= @card.author %></td>
  </tr>
  <tr>
    <th>価格</th><td><%= @card.price %></td>
  </tr>
  <tr>
    <th>出版社</th><td><%= @card.publisher %></td>
  </tr>
  <tr>
    <th>コメント</th><td><%= @card.memo %></td>
  </tr>
</table>
<p><a href="/cards">&lt;&lt;
  ※トップページに戻る
</a></p>

app/views/hello/index.html.erb
<p><%= @msg %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/cards.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cards</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="http://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
  <style>
    h1 { margin:25px 0px; }
    p { margin:25px 0px; }
  </style>
</head>

<body class="container">
  <%= yield %>
</body>
</html>

app/views/layouts/hello.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% @title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="conrtainer text-body">
  <%= render template: 'layouts/hello_header' %>
  <%= yield %>
  <%= render template: 'layouts/hello_footer' %>
</body>
</html>

app/views/layouts/hello_footer.html.erb
<div class="mt-5 text-right small text-dark border-bottom border-dark">
  <%= @footer %>
</div>

app/views/layouts/hello_header.html.erb
<h1 class="display-4 text-center mt-1 mb-4 text-primary">
  <%= @header %>
</h1>

app/views/layouts/msgboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
</head>

<body class="container text-body">
  <h1 class="mb-4 display-4 text-primary">MsgBoard</h1>
  <%= yield %>
  <div class="mt-4 text-center small text-dark border-top border-dark">copyright SYODA-Tuyano. 2020</div>
</body>
</html>

app/views/layouts/people.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <script src="https://kit.fontawesome.com/8cc3d59850.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'people', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/msgboard/index.html.erb
<%= form_tag(controller: "msgboard", action: "index") do %>
  <div class="form-group">
    <label for="name">名前</label>
    <%= text_field_tag("name","",{class:"form-control"}) %>
  </div>
  <div class="form-group">
    <label for="name">メール</label>
    <%= text_field_tag("mail","",{class:"form-control"}) %>
  </div>
  <div class="form-group">
    <label for="name">メッセージ</label>
    <%= text_area_tag("msg","",{class:"form-control"}) %>
  </div>
  <%= submit_tag("Click", {class: "btn btn-primary"}) %>
<% end %>

<table class="table mt-4">
  <tr>
    <th style="width: 50%">メッセージ</th>
    <th>名前</th>
    <th>メール</th>
    <th>投稿日時</th>
  </tr>
  <% @msg_data.each do |key,obj| %>
  <tr>
    <td class="msg"><%= obj['msg'] %></td>
    <td class="name"><%= obj['name'] %></td>
    <td class="mail"><%= obj['mail'] %></td>
    <td class="time"><%= Time.at(key.to_i ) %></td>
  </tr>
  <% end %>
</table>

app/views/people/edit.html.erb
<h1 class="display-4 text-primary">People#edit</h1>
<p><%= @msg %></p>
<%= form_with model: @person,local:true do |f|%>
  <div class="form-group">
    <%= f.label :Name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Age %>
    <%= f.text_field :age, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Mail %>
    <%= f.text_field :mail, class:'form-control' %>
  </div>
  <%= f.submit clss:'btn btn-primary' %>
<% end %>

app/views/people/find.html.erb
<h1 class="display-4 text-primary">People#Find</h1>
<p><%= @msg %></p>
<%= form_with model: @people, url: {controller: 'people', action: 'find' }, local:true do |f| %>
<div class="form-group">
  <%= f.label :FInd %>
  <%= f.search_field, class :"form-control" %>
</div>
<%= f.submit %>

<table class="table">
  <tr>
    <th>ID</th><th>Name</th><th>Age</th><th>Mail</th>
  </tr>
  <% @people.each do |obj| %>
  <tr>
    <td><%= obj.id %></td>
    <td><%= obj.name %></td>
    <td><%= obj.age %></td>
    <td><%= obj.mail %></td>
  </tr>
  <% end %>
</table>

app/views/people/index.html.erb
<h1 class="display-4 text-primary">People#index</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>ID</th><th>Name</th><th></th>
  </tr>
  <% @data.each do |obj| %>
  <tr>
    <td><%= obj.id %></td>
    <td><a href="/people/<%= obj.id %>">
      <%= obj.name %></a></td>
    <td>
      <a href="/people/<%= obj.id %>/edit">Edit</a>&nbsp;&nbsp;
      <a href="javascript:delData(<%= obj.id %>);">Delete</a>
    </td>
  </tr>
  <% end %>
</table>
<script>
function delData(num) {
  if (confirm('このデータを削除しますか？')) {
    document.location = "/people/" + num;
  }
  return false;
}
</script>

app/views/people/new.html.erb
<h1 class="display-4 text-primary">People#new</h1>
<p><%= @msg %></p>
<%= form_with model: @person,local:true do |f| %>
  <div class="form-group">
    <%= f.label :Name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Age %>
    <%= f.text_field :age, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Mail %>
    <%= f.text_field :mail, class:'form-control' %>
  </div>
  <%= f.submit clss:'btn btn-primary' %>
<% end %>

app/views/people/show.html.erb
<h1 class="display-4 text-primary">People#show</h1>
<p><%= @msg %></p>
<table class="table">
  <tr><th>ID</th>
    <td><%= @data.id%></td></tr>
  <tr><th>Name</th>
    <td><%= @data.name%></td></tr>
  <tr><th>Age</th>
    <td><%= @data.age%></td></tr>
  <tr><th>Mail</th>
    <td><%= @data.mail%></td></tr>
  </tr>
</table>